/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gcinterceptor_core_GC */

#ifndef _Included_com_gcinterceptor_core_GC
#define _Included_com_gcinterceptor_core_GC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gcinterceptor_core_GC
 * Method:    force
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gcinterceptor_core_GC_force
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
